SET GLOBAL SQL_MODE = CONCAT(@@SQL_MODE, ',ONLY_FULL_GROUP_BY');

SELECT DISTINCT l1.ID_S, l2.ID_S
FROM SPJ l1, SPJ l2
WHERE l1.ID_S != l2.ID_S
  AND l1.ID_P = l2.ID_P
  AND l1.QTY = l2.QTY
  AND l1.ID_S < l2.ID_S;
