SET GLOBAL SQL_MODE = CONCAT(@@SQL_MODE, ',ONLY_FULL_GROUP_BY');

SELECT COUNT(DISTINCT ea1.SSN2) P1, COUNT(DISTINCT ea2.SSN2) P2
FROM estami ea1, estami ea2
WHERE ea1.SSN1 = 'P1'
  AND ea2.SSN1 = 'P2';
